##############################################
# Criado por Kami, Forum SuperNation.com.br  #
##############################################
# Acesse: SuperNation.com.br                 #
##############################################

# MySQL
Use MySQL: false
dbname: 'teste' #Nome da database
url: 'localhost' #Endereço
user: 'root' #Usuario
senha: '1234' #Senha

# Configuracoes do plugin
Prefixo: '&f[&6Kami&eCaixas&f]'
Inicio contagem: ' §e Seus pontos para habilitar caixas começaram a contar a partir de agora.'
Matou: '&c Voce matou: @player §ee recebeu mais 1 ponto por isso'
Matou mas nao ganhou: '&c Voce matou: @player §e, mas não recebeu nenhum ponto por isso, porque ele tem 0 pontos'
Morreu: '&c @player matou você. Você perdeu 1 ponto por isso.'
Morreu mas nao perdeu: '&c Voce morreu, mas não perdeu nenhum ponto porque seus pontos são iguais a 0.'

# Itens do sorteio
Itens:
- '1; 1'
- '2; 1'
- '3; 1'
- '4; 1'
- '5; 1'
- '6; 1'
- '7; 1'
- '8; 1'
- '9; 1'
- '10; 1'
- '11; 1'